---
- name: Install nginx1.12 from amazon-linux-extras
  command: amazon-linux-extras install nginx1.12 -y
  become: yes
  args:
    creates: /usr/sbin/nginx

- name: create nginx paths
  file:
    path: /etc/nginx/{{ item }}
    state: directory
  become: yes
  with_items:
    - sites-available
    - sites-enabled

- include: copy_files.yml
- include: code_path.yml
- include: pid_bug.yml

- include_tasks: hosts.yml
  vars:
    server_name: "{{ item.map }}"
    directory: "{{ item.to }}"
    php_version: "{{ item.php | default ('7.2')}}"
    ssl: "{{ item.ssl | default (False) }}"
    cache_policies: "{{ item.cache | default ()}}"
  loop: "{{ sites }}"

- name: Change lib nginx ownership to ec2-user
  file:
    path: /var/lib/nginx
    owner: ec2-user
    group: ec2-user
    recurse: yes
  become: yes

- name: Reload nginx
  service:
    name: nginx
    state: reloaded
    enabled: yes
  become: yes
