---
- name: Install nginx1.12 from amazon-linux-extras
  command: amazon-linux-extras install nginx1.12 -y
  become: yes
  args:
    creates: /usr/sbin/nginx

- include_tasks: copy-conf-files.yml
- include_tasks: create-paths.yml
- include_tasks: pid-bug.yml
- include_tasks: sites-loop.yml
  when: sites

- name: Change lib nginx ownership to "{{ nginx_user }}"
  file:
    path: /var/lib/nginx
    owner: "{{ nginx_user }}"
    group: "{{ nginx_user }}"
    recurse: yes
  become: yes

- name: Reload nginx
  service:
    name: nginx
    state: reloaded
    enabled: yes
  become: yes
