---
- name: Set php fpm listener
  set_fact:
    php_fpm_listener: "{{ current.listener }}"
  with_items: "{{ php_fpm_listeners }}"
  loop_control:
    loop_var: current
  when: current.version == php_version

- name: Check if has ssl config
  set_fact:
    ssl_certificate: "{{ ssl.certificate }}"
    ssl_certificate_key: "{{ ssl.key }}"
  when: ssl

- name: Copy nginx file without ssl
  template:
    src: templates/sites/default.j2
    dest: /etc/nginx/sites-available/{{ server_name }}
  become: yes
  when: not ssl

- name: Copy nginx file with ssl
  template:
    src: templates/sites/ssl.j2
    dest: /etc/nginx/sites-available/{{ server_name }}
  become: yes
  when: ssl

- name: Enable in nginx
  file:
    src: /etc/nginx/sites-available/{{ server_name }}
    dest: /etc/nginx/sites-enabled/{{ server_name }}
    state: link
  become: yes

- name: Print in /etc/hosts
  lineinfile:
    path: /etc/hosts
    line: '{{ ansible_host }} {{ server_name }}'
  become: yes
